- JOB: "intercept -g $DEVNODE | caps2esc -m 1 | space2meta -t 200 | dual-function-keys -c /home/daf/fig/keyboard/dual-function-keys.yaml | uinput -d $DEVNODE"
  DEVICE:
    EVENTS:
      EV_KEY: [KEY_ENTER]
