  # TODO Set zsh as shell?

- name: Install zsh package
  become: true
  dnf:
    name:
      - zsh
    state: present
  when: ansible_distribution == "Fedora"

- name: Symlink zshrc
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/zshrc"
    path: "/home/{{ ansible_env.USER }}/.zshrc"
    state: link

- name: Symlink zsh config
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/zsh"
    path: "/home/{{ ansible_env.USER }}/.config/zsh"
    state: link

- name: Set default shell to zsh
  ansible.builtin.command: usermod --shell /usr/bin/zsh {{ ansible_env.USER }}
  become: true
  changed_when: false
  when: ansible_distribution == "Fedora"
