- name: Install dunst package
  become: true
  dnf:
    name:
      - dunst
    state: present
  when: ansible_distribution == "Fedora"

- name: Symlink dunst config
  file:
    src: "{{ ansible_env.PWD }}/roles/dunst/files/dunst"
    path: "/home/{{ ansible_env.USER }}/.config/dunst"
    state: link
