- name: Install imv package
  become: true
  dnf:
    name:
      - imv
    state: present
  when: ansible_distribution == "Fedora"

- name: Symlink imv
  file:
    src: "{{ ansible_env.PWD }}/roles/imv/files/imv"
    path: "/home/{{ ansible_env.USER }}/.config/imv"
    state: link
