- name: Install foot package
  become: true
  dnf:
    name:
      - foot
    state: present
  when: ansible_distribution == "Fedora"

- name: Symlink foot config
  file:
    src: "{{ ansible_env.PWD }}/roles/foot/files/foot"
    path: "/home/{{ ansible_env.USER }}/.config/foot"
    state: link
